#!/bin/bash -e

CODENAME=$(lsb_release -c | cut -f2)

POLIPO_PORT=8124
FAB_PATH=/turnkey/fab

# create directory structure
mkdir -p $FAB_PATH/bootstraps
mkdir -p $FAB_PATH/products
mkdir -p $FAB_PATH/pools/$CODENAME
mkdir -p $FAB_PATH/chankos/$CODENAME.chanko/{config,plan}

# set up pool


# setup chanko
cat /etc/apt/sources.list.d/*.list > $FAB_PATH/chankos/$CODENAME.chanko/config/sources.list
cat /etc/apt/

# environmental variables and bash tweaks
mkdir -p /root/.bashrc.d

cat >/root/.bashrc.d/fab<<EOF
export FAB_PATH=$FAB_PATH
export FAB_APT_PROXY=http://127.0.0.1:$POLIPO_PORT
export FAB_HTTP_PROXY=http://127.0.0.1:$POLIPO_PORT
EOF
chmod +x /root/.bashrc.d/fab

cat >/root/.bashrc.d/turnkey-paths<<EOF
CDPATH=.:$FAB_PATH:/turnkey:$FAB_PATH/products
export _CDPATH=\$CDPATH
EOF
chmod +x /root/.bashrc.d/turnkey-paths

# polipo
chmod -x /etc/cron.daily/polipo
cat >> /etc/polipo/config <<EOF

proxyPort = $POLIPO_PORT
dnsNameServer = 8.8.8.8
EOF

# disable services so as not to conflict with builds
sysv-rc-conf webmin off
sysv-rc-conf stunnel4 off
sysv-rc-conf shellinabox off
sysv-rc-conf postfix off

