#!/bin/bash -e

# set vars
FAB_PATH=/turnkey/fab
CODENAME=$(lsb_release -cs)
PROD_PATH=$FAB_PATH/products
BUILDTASKS=/mnt
PROXY_PORT=3128
POOL_PATH=$FAB_PATH/pools/$CODENAME

## configure squid
# bump max file descriptors
OVERRIDE=etc/systemd/system/squid.service.d/override.conf
mkdir -p $(dirname $OVERRIDE)
cat > $OVERRIDE <<EOF
[Service]
LimitNOFILE=65535
EOF
# leverage firstboot script to configure TLS interception (DRY)
/usr/lib/inithooks/firstboot.d/20regen-proxy-cert
# use squid for future apt caching; but change the name
# (otherwise it will be removed at end of build process)
mv /etc/apt/apt.conf.d/01proxy /etc/apt/apt.conf.d/00proxy
# when built on TKLDev <17.0 the port will be wrong
sed -i "s|8124|$PROXY_PORT|" /etc/apt/apt.conf.d/00proxy

# create base directory structure
mkdir -p $FAB_PATH/bootstraps \
         $PROD_PATH \
         $BUILDTASKS/{isos,builds}

# environmental variables and bash tweaks
mkdir -p /root/.bashrc.d

cat >/root/.bashrc.d/fab<<EOF
export FAB_PATH=$FAB_PATH
export FAB_HTTP_PROXY=http://127.0.0.1:$PROXY_PORT
# https proxy must be connected to via http
export FAB_HTTPS_PROXY=http://127.0.0.1:$PROXY_PORT
EOF
chmod +x /root/.bashrc.d/fab

cat >/root/.bashrc.d/turnkey-paths<<EOF
CDPATH=.:$FAB_PATH:/turnkey:$FAB_PATH/products
export _CDPATH=\$CDPATH
EOF
chmod +x /root/.bashrc.d/turnkey-paths

# disable confconsole auto run on firstboot
CONF=/etc/confconsole/confconsole.conf
sed -i "s|^autostart.*|autostart false|g" $CONF

# disable services so as not to conflict with builds
systemctl disable webmin
systemctl disable webmin@stunnel4
systemctl disable shellinabox
systemctl disable shellinabox@stunnel4
systemctl disable postfix
