#!/bin/bash -e

# This script regenerates squid MITM proxy CA cert (to generate valid SSL/TLS
# certs on the fly)

# Preperation
DAYS_VALID=3650 # ten years...
CERT_D=/etc/squid/cert/
CERT=$CERT/squid_proxyCA.pem
CA_CRT=/usr/local/share/ca-certificates/squid_proxyCA.crt
mkdir -p $CERT_D $(dirname $CA_CRT)
rm -rf $CERT $CA_CRT

# Generate local self-signed CA certificate/key (in the same file)
openssl req -config /etc/squid/tkl-openssl.cnf -new -newkey rsa:4096 -sha256 \
    -days $DAYS_VALID -nodes -x509 -keyout $CERT -out $CERT
chown -R proxy:proxy $CERT_D
chmod 0400 $CERT

# Add squid_proxyCA cert to system trusted CAs (so squid cert is trusted by
# default)
openssl x509 -inform PEM -in $CERT -outform PEM -out $CA_CRT
update-ca-certificates
