#!/bin/bash -e
# setup/update system ready for building appliances

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
info() { echo "INFO [$(basename $0)]: $@"; }

GPGKEY="A16EB94D"
IMAGES="http://mirror.turnkeylinux.org/turnkeylinux/images"
FAB_PATH="/turnkey/fab"
BOOTSTRAP_NAME="bootstrap-$(lsb_release -s -c)-$(dpkg --print-architecture)"
BOOTSTRAP_PATH="$FAB_PATH/bootstraps/$(lsb_release -s -c)"

if [ ! -d $BOOTSTRAP_PATH ]; then
    info "downloading $BOOTSTRAP_NAME"
    mkdir -p $(dirname $BOOTSTRAP_PATH)
    cd $(dirname $BOOTSTRAP_PATH)
    wget -nc $IMAGES/bootstrap/$BOOTSTRAP_NAME.tar.gz
    wget -nc $IMAGES/bootstrap/$BOOTSTRAP_NAME.tar.gz.sig

    info "verifying $BOOTSTRAP_NAME"
    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 0x$GPGKEY
    gpg --verify $BOOTSTRAP_NAME.tar.gz.sig

    info "unpacking $BOOTSTRAP_NAME"
    mkdir $BOOTSTRAP_PATH
    tar -zxf $BOOTSTRAP_NAME.tar.gz -C $BOOTSTRAP_PATH
fi

g() {
    src=https://github.com/$1
    dst=$2
    mkdir -p $(dirname $dst)
    if [ -d $dst ]; then
        info "updating $dst"
        GIT_DIR=$dst/.git git pull
    else
        info "cloning $src"
        git clone $src $dst
    fi
}

g turnkeylinux/cdroots $FAB_PATH/cdroots
g turnkeylinux/common $FAB_PATH/common
g turnkeylinux-apps/core $FAB_PATH/products/core

